### ISSUE TITLE
Is there any way to combine both EsiPy and PyCrest?

### ISSUE THREAD

**Issue by pennyarcade** [Kyria/EsiPy#13]
Hello,

I'd like to use EsiPy as the lead library as the EVE Online ESI API is developed and fall back pn PyCrest where there is no ESI endpoints yet.

I'd also like to use ons SSO session for both, Authenticating via EsiPy.

Is there any way to pass the recieved OAuth session to PyCrest?

Regards, Martin

**Comment by Kyria** [comment]
Hello,

Yes of course you can :) 

To start, you first need to store your access/refresh tokens after you do an `EsiSecurity.auth(code)` or `EsiSecurity.refresh()` _(You can also access it from your security attribute `access_token` and `refresh_token`)_

Once you have this, from pycrest, you have 2 solutions: 

1. Create an EVE object then use the `temptoken_authorize()` method to get your authed pycrest handler [[See API](https://github.com/pycrest/PyCrest/blob/master/pycrest/eve.py#L277)

2. You can directly instanciate an `AuthedConnection` and use it normally
```python
from pycrest import AuthedConnection

authed_pycrest = AuthedConnection(
    {
        'access_token': access_token_from_esipy,
        'refresh_token': refresh_token_from_esipy,
        'expires_in': expires_in_from_esipy
    },
    'https://crest-tq.eveonline.com',
    'https://login.eveonline.com/oauth',
    'YOUR_CLIENT_ID',
    'YOUR_SECRET_KEY',
    # cache=None, or whatever you want, if you don't know, don't include it and leave default
)
```

And then you can use it like you'd use pycrest without esipy. Just be aware that, since PyCrest auto refreshes the token, you may lose the new token if you save them somewhere. So if you save them / if you care of it, you have to manually check and update before using pycrest. 

-----

In the same way, in case someone might want to know that, you can do the same with XML API using tokens, using a lib like [evelink](https://github.com/eve-val/evelink). 
[Little example with something I do already](https://github.com/Kyria/LazyBlacksmith/blob/master/lazyblacksmith/tasks/corporation/blueprints.py#L72-L73)
