### ISSUE TITLE
Question on ThreadPoolExecutor vs. asyncio

### ISSUE THREAD

**Issue by EricE** [Kyria/EsiPy#15]
I see that you are using ThreadPoolExecutor for concurrent requests.  Isn't ProcessPoolExecutor more efficient for these kinds of queries?  With asynico I was easily running into the rate limits with CREST.  I've taken a six month break from Eve and need to convert my tools to ESI and considering whether to use EsiPy or update my asyncio based code.

**Comment by Kyria** [comment]
Why not asyncio: because python 2 support. 
And trollius (the py2 port of asyncio) is not exactly the same, so it may require double work. Also I wanted to use the least possible external libraries (thus avoiding things that requires additional libs, such as trollius). 

About `ThreadPoolExecutor` vs `ProcessPoolExecutor`, we are not bound to CPU tasks but I/O tasks, and since I/O tasks are not affected by python GIL (or to say it better, i/o releases the GIL until data are returned), multi threading is enough.

After, to be honest, I don't really see the advantage of doing multiprocessing (which may work fine, as long as the user have more than 1 core) or using asyncio/trollius over multithreading for the current case which is a simple use of it. 

I might also miss something, so if i'm wrong please tell me :)

**Comment by EricE** [comment]
I apologize, between writing the title and the body I figured out the 2.x limitation of asyncio but was very tired and forgot to update it...  Also was confused about cpu vs. io bound.  For some reason I thought asyncio used a process model vs threading...  In my day job I'm a hardware guy and do most of my Python with Eve and it has been a while.  Trying hard to get back to Eve and Python :)  Thanks for your active support, it makes me more confident of using your library vs. rolling my own (had started with pycrest but the dev seemed to drop it pretty quickly)
