### ISSUE TITLE
Ability to throw exception when a request fails

### ISSUE THREAD

**Issue by blitzmann** [Kyria/EsiPy#34]
Hey there!

Right now, if the server returns a 502 (happens occasionally when TQ is down), ESI returns that response and it's up to the client to handle it. Would it be possible to include a flag for the `EsiClient` to check the response and, if `resp.status != 200` then raise an Exception, with the resp as an argument? This will prevent app developers from having to wrap all their specific calls in a function to check the status, and can thus clean up the code a bit, and since it's a flag it can be optional for those who would need it.

Not super important or anything, just wanted to start discussion. If it's something that you are okay with, I can submit a PR to include the needed changes.

**Comment by blitzmann** [comment]
Also, full disclosure, this is kind of stemming from https://github.com/pyfa-org/Pyfa/issues/1537. I was under the assumption (without checking of course :P) that failed requests threw an exception, thus I wasn't handling it properly myself. :)

**Comment by Kyria** [comment]
Well, i'm only half okay with that. 
Even if I can understand the logic / use of that change, I don't think it's the lib job to send an exception, especially as all responses different from HTTP 200 are also valid ESI responses (502 included)... 

We could still add a "raise_for_error" or something flag (defaulted to false) for those that want it, but this need to have both status and content (because you might want to check it), just like `requests` does with its `reponse.raise_for_status()` for those that want an exception.

**Comment by blitzmann** [comment]
> I don't think it's the lib job to send an exception

As mentioned, certain http libraries do this by default, while others provide a method, such as `requests`. I do believe it would be helpful as it is almost always the case when you don't receive a successful status code, you want to handle it somehow, which IMO is a job for exceptions, and being an ESI client, I would have thought EsiPy would be the one to determine "the request failed, I didn't actually do what you needed me to do"
 
> but this need to have both status and content

Aye, my thought was was to simply return the response object as `raise EsiException(resp)`, that way if someone needs to dig deeper (take a look at the code, the content, or anything involving the response) they have access to that.

As said, I have a wrapper in my code that checks for an error'd response (status >= 400). this works well and I can continue using this no problem, but doing this for each individual call is kinda annoying, and I thought it might be useful if it was included directly within the library. :) Let me know what you decide!

And thanks for you're continued work! pyfa 2.0 Stable with ESI support coming out tonight hopefully!

**Comment by Kyria** [comment]
After some thought I think I will add a parameter that'll allow to have an exception raised if status >= 400.

Why this:
* If I make it global, for the "multi_request", it'll have weird / unwanted behavior: either exception will not do anything, since everything is within a `ThreadPoolExecutor`, or it'll break all request if only one fail, which is not necessarily what the user will want, because this method uses `request()` to do the actual request at the end.
* If I make it local, users can request it on need, but they'll have to always add a param `raise_on_error` to the requests (but it's not worse than having to add a `response.raise_for_status()` imho).

Any thoughts ?

**Comment by Kyria** [comment]
released in 0.4.0, thanks !

**Comment by blitzmann** [comment]
Sorry, never saw the previous post. Think this would be a great addition 😄
