### ISSUE TITLE
'User-agent' does not work well

### ISSUE THREAD

**Issue by hidesoon** [Kyria/EsiPy#43]
Today I received an Error 420 when I launched my [own app](https://github.com/hidesoon/evelearning).

```py
Defining a 'User-Agent' header is a good practice, and allows CCP to contact you if required. To do this, simply add the following when creating the client: headers={'User-Agent':'something'}.

xxx\\app\\venv\\lib\\site-packages\\esipy\\[security.py:118](https://security.py:118): UserWarning: Defining a 'User-Agent' header is a good practice, and allows CCP to contact you if required. To do this, simply add the following when creating the client: headers={'User-Agent':'something'}.

  warnings.warn(warning\_message)

Traceback (most recent call last):

  File "<input>", line 125, in <module>

  File "<input>", line 93, in refresh\_tokens

  File "xxx\\app\\venv\\lib\\site-packages\\esipy\\[security.py](https://security.py)", line 313, in verify

response\_header=res.headers

esipy.exceptions.APIException: HTTP Error 420: This software has exceeded the error limit for ESI. If you are a user, please contact the maintainer of this software. If you are a developer/maintainer, please make a greater effort in the future to receive valid responses. For tips on how, come have a chat with us in #esi on tweetfleet slack. If you're not on tweetfleet slack yet, you can get an invite here -> [https://www.fuzzwork.co.uk/tweetfleet-slack-invites/](https://www.fuzzwork.co.uk/tweetfleet-slack-invites/)
```

May I ask your help to solve this issue?

Root cause: I have tried different way to solve this warning, but whatever the user-agent header I use,, It would always get the warning.

I currently use headers={'User-Agent':'the_name_of_my_app'}.

Q1: How to define the user-agent without warning? the instruction of 'something' is too blur to me. Is this a pyesi specific problem?

Q2: Now, I realised that even a warning count as an error. It that correct?

Q3: As I already got the 420 error, how could I solve this error,, reset the access of ESP?

Q4: I joined Slack Tweetfleet, but why I can't see any thread or channel?

Sorry, maybe too many questions.

Thank you in advance!!!

**Comment by Kyria** [comment]
Actually you have 2 issues here:
- one is not a real issue, just a warning from EsiPy about headers
- the second is your 420, which mean you get too much error 4XX/5XX from ESI so you need to review how you do your work. 

1) https://github.com/hidesoon/evelearning/blob/master/app/main.py#L44 --> add the headers argument here. (There's a typo in the message, forgot to change "client" for "security")

2) no, EsiPy warning is not counted in error and independant from ESI (it's only client side). 
You need to log what call you do, which give you 4xx / 5xx errors and make sure you have less, because this is only from errors you have while dealing with ESI itself. 

3) above / join the channel #esi on slack,

4) click on "channels" line in slack, then look for "#esi". Actually if you joined the tweetfleet slack you should already be in #devfleet, then you can find in the MOTD (in the top of the windows, the message) a link to this channel :)
