### ISSUE TITLE
EsiPy crashes when 504 Gateway Time-out is given

### ISSUE THREAD

**Issue by mcgibbon** [Kyria/EsiPy#49]
Since very recently (the past month?), I've been regularly getting crashes in EsiPy when ESI has a gateway time-out. This hadn't ever happened in the prior 6 months of my using this application, and I've made no changes to it recently.

```
File "C:\Users\Jeremy\python\eve\esi.py", line 120, in <lambda>                                                           
  lambda *args, **kw: self.esiClient.request(self.app.op[op_name](**kw)),                                               
File "C:\Users\Jeremy\Anaconda3\lib\site-packages\esipy\client.py", line 124, in _retry_request                           
  res = self._request(req_and_resp, **kwargs)                                                                           
File "C:\Users\Jeremy\Anaconda3\lib\site-packages\esipy\client.py", line 232, in _request                                 
  raw=six.BytesIO(res.content).getvalue()                                                                               
File "C:\Users\Jeremy\Anaconda3\lib\site-packages\pyswagger\io.py", line 416, in apply_with                               
  data = self.__op._mime_codec.unmarshal(content_type, self.raw, _type=_type, _format=_format, name=name)               
File "C:\Users\Jeremy\Anaconda3\lib\site-packages\pyswagger\primitives\codec.py", line 34, in unmarshal                   
  raise Exception('Could not find codec for %s, data: %s, args: %s' % (mime, data, kwargs))                           

Exception: Could not find codec for text/html, data: b'<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor="white">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n</body>\r\n</html>\r\n', args: {'_type': 'object', '_format': None, 'name': 'gateway_timeout'} 
```

There may have been some change in the errors CCP is giving out that has caused this. Any ideas?

**Comment by mcgibbon** [comment]
I tried using [this workaround](https://github.com/pyopenapi/pyswagger/issues/104), but it didn't work (there was no change).

**Comment by Kyria** [comment]
Can't really do something about it (as it's 100% CCP side in AWS load balancers actually iirc) but just "catch" `Exception` and throw it back to you as `APIException`, which doesn't make any sense imho, and is dangerous as it's a generic `Exception` instead of a specific one.

This can, and will continue to, happen sadly. 
Best thing to do is to catch exceptions yourside (which you should already do anyway) and try again if it happens.

**Comment by mcgibbon** [comment]
It's a bit annoying since CCP has [said](https://github.com/esi/esi-issues/issues/1102) they won't fix this ("it's upstream so nothing we can do").

I've worked around the issue by adding in a text/html handler that converts any html into an error dictionary, similar to the suggestion in [this issue](https://github.com/pyopenapi/pyswagger/issues/104). The problem of "catching" the exception in my code is that it prevents EsiPy's retry mechanism from working, meaning I'd have to write my own retry code. This workaround avoids that issue.

**Comment by Kyria** [comment]
Well, any exception raised in EsiPy will prevent retry anyway, either mine (APIException) or those behind (from pyswagger and deeper), so any cases, you'll have the same behavior.

I'll have a look at your link, maybe something can be done, but I won't promise anything (since it's not the lib job to catch these types of errors)
