### ISSUE TITLE
[Question] Does EsiPy back off accordingly for X-Esi-Error-Limit-Remain?

### ISSUE THREAD

**Issue by porowns** [Kyria/EsiPy#52]
Does EsiPy back off accordingly for X-Esi-Error-Limit-Remain when using request() on EsiClient?

**Comment by Kyria** [comment]
Currently, no and I didn't really plan to do it because it would require to store this data somewhere in EsiClient, add threshold and sleep mechanism I didn't want to have in it. 

I'm always open to discuss it, but I don't really feel the need to have such mechanism in EsiPy when many users won't ever have the use of it.

**Comment by porowns** [comment]
I'm doing a lot of wrapping for the EsiPy client as of lately to speed things up, was wondering if I should just contribute to this directly instead of having silly wrappers everywhere. 

e.g recently wrapped EsiApp.get_latest_swagger to store it in memcached, because it's a ridiculous wait to keep pulling things like that. 

I was going to do the same thing and write the ESI limit to memcached, that way with my 64+ workers it's not going to nuke my error limit. Do you think it would be better to contribute it directly to EsiClient?

**Comment by Kyria** [comment]
> e.g recently wrapped EsiApp.get_latest_swagger to store it in memcached, because it's a ridiculous wait to keep pulling things like that.

This already exists ... ? But by default the cache time from the endpoint is 1min, so you have to set it yourself to more... (else you'd do head() -> etag -> potential update each time)
https://kyria.github.io/EsiPy/getting_started/esiapp/#how-to-use-it 

> I was going to do the same thing and write the ESI limit to memcached, that way with my 64+ workers it's not going to nuke my error limit. Do you think it would be better to contribute it directly to EsiClient?

Really depends on where and how you would do it. 
Currently, the only useful place I can see to add it (within the lib I mean) is to check for the header if we allow auto retry, to wait for it. In the request itself, I don't think it'll be any help (as we cannot predict it, but only react to it) ?
Or am I missing something ?

**Comment by porowns** [comment]
> This already exists ... ? But by default the cache time from the endpoint is 1min, so you have to set it yourself to more... (else you'd do head() -> etag -> potential update each time)
https://kyria.github.io/EsiPy/getting_started/esiapp/#how-to-use-it

I think my use case is a little bit different, I was expecting the cache to create something static, that way when I get EsiApp again it'll not have to rebuild the spec again.

e.g
```
from esipy import EsiApp

# Normal
app_with_5min_cache = EsiApp(cache_time=300).get_latest_swagger # 8 seconds
app_with_5min_cache = EsiApp(cache_time=300).get_latest_swagger # 10 seconds

# With cache
app_with_5min_cache = EsiApp(cache_time=300).get_latest_swagger # 8 seconds
cache.set('esi_app', app_with_5min_cache)
cache.get('esi_app', app_with_5min_cache) # 0.25 seconds
```

Since I run my ESI calls with celery, everything is async so I need to create EsiApp every time for the whatever thousand tasks that are running 

> Currently, the only useful place I can see to add it (within the lib I mean) is to check for the header if we allow auto retry, to wait for it. In the request itself, I don't think it'll be any help (as we cannot predict it, but only react to it) ?

Yeah, it would be a reaction thing. For example, the way I currently have implemented it for my project: Check the header when getting my EsiClient object (cached in memcached so that all my workers can access it), if we aren't able to have anymore errors, don't return EsiClient.

**Comment by Kyria** [comment]
Your first caching method is not persistent, that's why you have that "duration" issue: you have 2 instance of cache in each EsiApp() which do not cache the same place. 
Instead do the same but provide EsiApp() the cache object so it knows where to cache (and do not create a DictCache)

```python
# can't test that right now, but it's supposed to work :) 
import memcache 
from esipy import EsiApp
from esipy.cache import MemcachedCache

mc = memcache.Client(['127.0.0.1:11211'], debug=0)
cache = MemcachedCache(memcache_client=mc)
app_with_5min_cache = EsiApp(cache=cache, cache_time=300).get_latest_swagger # 8 seconds
app_with_5min_cache = EsiApp(cache=cache, cache_time=300).get_latest_swagger # should take around the same duration of your "speed test" so probably <1sec
```

For the rate limit: I cannot return nothing, from the .request(), it wouldn't be consistent. I could return also an exception (which is already the case I think if you set `raise_on_error` to true in the `request()` parameters) or a valid error response object (which I believe is the case also). 

I cannot set the behavior based on that header simply because many users will not deal with that header the same depending on their use. I personally don't care for example, as if I have a fail due to 4xx or 5xx, I just rerun the celery task 5min later, but I don't have >50 calls per seconds anyway. 

The only thing that would make sense for me to react this, would be to deal with it in the [retry request](https://github.com/Kyria/EsiPy/blob/master/esipy/client.py#L126), and make the process wait for  `x-esi-error-limit-reset` seconds if `x-esi-error-limit-remain` is at 0. 

The behavior you describe is better in the client I think, as it's based one your need. You could also use `raise_on_error`, and catch APIException and check the header for rate limit.

**Comment by porowns** [comment]
> Your first caching method is not persistent, that's why you have that "duration" issue: you have 2 instance of cache in each EsiApp() which do not cache the same place.
Instead do the same but provide EsiApp() the cache object so it knows where to cache (and do not create a DictCache)

Ah, I didn't realize there was a cache parameter.. just scrolled down on the documentation and realized the "API" section.. my bad!

> The behavior you describe is better in the client I think, as it's based one your need. You could also use raise_on_error, and catch APIException and check the header for rate limit.

Since there is a `cache` parameter in EsiClient, it'd be possible to store the previous `x-esi-error-limit-remain` value in the cache (if set) and then take action (e.g raise an error) based on that?
